### ISSUE TITLE
Unable to add new calls after the execution of previous calls

### ISSUE THREAD

**Issue by sebdesign** [chadhutchins/codeigniter-mcurl#1]
``` php
$this->load->library('mcurl');
$this->mcurl->add_call("get","http://foo.com");
$this->mcurl->add_call("get","http://bar.com");
$responses = $this->mcurl->execute();

$this->mcurl->add_call("get","http://baz.com");
// PHP Warning: curl_multi_add_handle(): 42 is not a valid cURL handle resource in qux.php on line 42
```

I'm adding a few calls which are executing fine, without bugs.
Later on I add some other calls and I receive a warning: _curl_multi_add_handle(): 42 is not a valid cURL Multi Handle resource._

This is caused because after the execution the curl multi handle is being closed. Therefore `$this->curl_parent` becomes a resource of type _Unknown_. When `$this->curl_parent` is reused in the curl functions it generates this warning and doesn't work.

In `$this->add_call()` you should check if `$this->curl_parent` is not closed, and if it is, you should initialize it again.
Here's a snippet I added just before the `curl_multi_add_handle()` at the end of the method:

``` php
if(get_resource_type($this->curl_parent) == 'Unknown')
{
    $this->curl_parent = curl_multi_init();
}
```

I know that the purpose of multi curl is to add all the calls before executing them, but I need to call and execute cURLs in different parts during the runtime, which I can't merge together. Also CI libraries should be reusable at any moment, and I think it would be handful to use it at any moment.

**Comment by sebdesign** [comment]
You should also clear the previous calls if you are adding another call after the execution. The revised snippet would be:

``` php
if(get_resource_type($this->curl_parent) == 'Unknown')
{
    $this->calls = array();
    $this->curl_parent = curl_multi_init();
}
```

And it should be added on the top of `$this->add_call()` just before the counting and creation of the new call.

**Comment by chadhutchins** [comment]
Hey there... thanks for reporting this. I would have replied sooner, but for some reason I didn't receive an email notification on this one. 

Feel free to fork, fix and send in the pull request and I'll get it added; otherwise, I'll try to update this myself soon.

Thanks again!

**Comment by chadhutchins** [comment]
Thanks to your pull request, this is fixed. Appreciate it!

**Comment by sebdesign** [comment]
You're welcome! This library is great. :)
