### ISSUE TITLE
[enhancement] ID in calls array and Accept cookies

### ISSUE THREAD

**Issue by mabdelfattah** [chadhutchins/codeigniter-mcurl#3]
Thanks a lot for your GREAT library, I just have 2 comments :

1st. I should be able to add a reference for each call, to use it when response back after execution.
for example : $this->mcurl->add_call("site_1", "get","https://ajax.googleapis.com/ajax/services/search/blogs",$vars,$options);

2nd, I think cookies should be enabled too.

**Comment by chadhutchins** [comment]
Yo... I appreciate it. Glad it has been useful.

1) I agree, that's a good enhancement idea. I wouldn't turn down a pull request with that enhancement ;) Not sure when I'll be able to get to it.

2) Regarding the cookies, are you talking about on the curl options, allow cookies? Can you give a usage example?

Thanks!

**Comment by chadhutchins** [comment]
I added in the feature to reference calls by a key name.

Also, for the cookie issue,  you should be able to do something like:

``` php

$curl_opts = array(
    CURLOPT_COOKIEJAR => '/php/cookies.txt',
    CURLOPT_COOKIEFILE => '/php/cookies.txt'
);

$this->mcurl->add_call("myCall","POST","http://whatever.com",array(),$curl_opts);

```

**Comment by mabdelfattah** [comment]
Great, well done man :)

BTW, I think you should include CURLOPT_TIMEOUT by default in source code too.
